
name: Reset Production Database (WARNING! Running this will reset the hosted database).
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v3
    
    - name: SSH into DigitalOcean Droplet 
      uses: appleboy/ssh-action@v0.1.8
      with: 
        host: ${{ secrets.SSH_HOST }} # Droplet IP Address
        username:  ${{ secrets.SSH_USERNAME }} # User we'll SSH into
        password:  ${{ secrets.SSH_KEY }} # Top-Secret Password!!!
        script : |
          docker-compose down
          docker volume rm root_backend_prod
          docker volume rm root_migrations
          docker-compose pull
          docker-compose up -d 